# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module Easyship
  module Operations
    autoload :CreateCompaniesResponse, 'easyship/models/operations/createcompanies_response.rb'
    autoload :SortBy, 'easyship/models/operations/sort_by.rb'
    autoload :SortDirection, 'easyship/models/operations/sort_direction.rb'
    autoload :ListCompaniesRequest, 'easyship/models/operations/listcompanies_request.rb'
    autoload :ListCompaniesResponse, 'easyship/models/operations/listcompanies_response.rb'
    autoload :UpdateCompaniesRequest, 'easyship/models/operations/updatecompanies_request.rb'
    autoload :UpdateCompaniesResponse, 'easyship/models/operations/updatecompanies_response.rb'
    autoload :CreateOrganizationsResponse, 'easyship/models/operations/createorganizations_response.rb'
    autoload :DeleteOrganizationsRequest, 'easyship/models/operations/deleteorganizations_request.rb'
    autoload :DeleteOrganizationsResponse, 'easyship/models/operations/deleteorganizations_response.rb'
    autoload :GetOrganizationsRequest, 'easyship/models/operations/getorganizations_request.rb'
    autoload :GetOrganizationsResponse, 'easyship/models/operations/getorganizations_response.rb'
    autoload :ListOrganizationsRequest, 'easyship/models/operations/listorganizations_request.rb'
    autoload :ListOrganizationsResponse, 'easyship/models/operations/listorganizations_response.rb'
    autoload :QueryParamSortBy, 'easyship/models/operations/queryparam_sort_by.rb'
    autoload :QueryParamSortDirection, 'easyship/models/operations/queryparam_sort_direction.rb'
    autoload :ListOrganizationCompaniesRequest, 'easyship/models/operations/listorganizationcompanies_request.rb'
    autoload :ListOrganizationCompaniesResponse, 'easyship/models/operations/listorganizationcompanies_response.rb'
    autoload :UpdateOrganizationsRequest, 'easyship/models/operations/updateorganizations_request.rb'
    autoload :UpdateOrganizationsResponse, 'easyship/models/operations/updateorganizations_response.rb'
    autoload :IntrospectTokenResponse, 'easyship/models/operations/introspecttoken_response.rb'
    autoload :RetrieveTokenResponse, 'easyship/models/operations/retrievetoken_response.rb'
    autoload :RetrieveInfoResponse, 'easyship/models/operations/retrieveinfo_response.rb'
    autoload :RevokeTokenResponse, 'easyship/models/operations/revoketoken_response.rb'
  end
end
