# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module Easyship
  module Shared
    autoload :CompanySingle, 'easyship/models/shared/company_single.rb'
    autoload :CompanyOwner, 'easyship/models/shared/company_owner.rb'
    autoload :Company, 'easyship/models/shared/company.rb'
    autoload :Organization, 'easyship/models/shared/organization.rb'
    autoload :CountryAlpha2, 'easyship/models/shared/countryalpha2.rb'
    autoload :Type, 'easyship/models/shared/type.rb'
    autoload :ErrorError, 'easyship/models/shared/error_error.rb'
    autoload :Error, 'easyship/models/shared/error.rb'
    autoload :CompanyCreate, 'easyship/models/shared/companycreate.rb'
    autoload :CompanyUserCreate, 'easyship/models/shared/companyusercreate.rb'
    autoload :Meta, 'easyship/models/shared/meta.rb'
    autoload :CompanyList, 'easyship/models/shared/company_list.rb'
    autoload :Pagination, 'easyship/models/shared/pagination.rb'
    autoload :CompanyUpdate, 'easyship/models/shared/companyupdate.rb'
    autoload :Owner, 'easyship/models/shared/owner.rb'
    autoload :OrganizationSingle, 'easyship/models/shared/organization_single.rb'
    autoload :OrganizationCreate, 'easyship/models/shared/organizationcreate.rb'
    autoload :SuccessSuccess, 'easyship/models/shared/success_success.rb'
    autoload :Success, 'easyship/models/shared/success.rb'
    autoload :OrganizationListMeta, 'easyship/models/shared/organization_list_meta.rb'
    autoload :OrganizationList, 'easyship/models/shared/organization_list.rb'
    autoload :OrganizationUpdate, 'easyship/models/shared/organizationupdate.rb'
    autoload :Platform, 'easyship/models/shared/platform.rb'
    autoload :OAuth2IntrospectResponse, 'easyship/models/shared/oauth2introspectresponse.rb'
    autoload :TokenType, 'easyship/models/shared/token_type.rb'
    autoload :OAuth2IntrospectRequest, 'easyship/models/shared/oauth2introspectrequest.rb'
    autoload :OAuth2TokenResponseTokenType, 'easyship/models/shared/oauth2tokenresponse_token_type.rb'
    autoload :OAuth2TokenResponse, 'easyship/models/shared/oauth2tokenresponse.rb'
    autoload :OAuth2ClientCredentialsRequestGrantType, 'easyship/models/shared/oauth2clientcredentialsrequest_grant_type.rb'
    autoload :OAuth2ClientCredentialsRequest, 'easyship/models/shared/oauth2clientcredentialsrequest.rb'
    autoload :Application, 'easyship/models/shared/application.rb'
    autoload :OAuth2TokenInfo, 'easyship/models/shared/oauth2tokeninfo.rb'
    autoload :RevokeAccessTokenResponse, 'easyship/models/shared/revokeaccesstokenresponse.rb'
    autoload :OAuth2TokenRevokeRequest, 'easyship/models/shared/oauth2tokenrevokerequest.rb'
    autoload :GrantType, 'easyship/models/shared/grant_type.rb'
    autoload :Security, 'easyship/models/shared/security.rb'
  end
end
