# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Operations
  

    class DeleteOrganizationsResponse < ::Easyship::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, ::String
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, ::Faraday::Response
      # HTTP response status code for this operation
      field :status_code, ::Integer
      # failed to delete the organization
      field :error, T.nilable(::Easyship::Shared::Error)
      # organization successfully deleted
      field :success, T.nilable(::Easyship::Shared::Success)


      sig { params(content_type: ::String, raw_response: ::Faraday::Response, status_code: ::Integer, error: T.nilable(::Easyship::Shared::Error), success: T.nilable(::Easyship::Shared::Success)).void }
      def initialize(content_type: nil, raw_response: nil, status_code: nil, error: nil, success: nil)
        @content_type = content_type
        @raw_response = raw_response
        @status_code = status_code
        @error = error
        @success = success
      end
    end
  end
end
