# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Operations
  

    class GetOrganizationsResponse < ::Easyship::Utils::FieldAugmented
      extend T::Sig

      # HTTP response content type for this operation
      field :content_type, ::String
      # Raw HTTP response; suitable for custom response parsing
      field :raw_response, ::Faraday::Response
      # HTTP response status code for this operation
      field :status_code, ::Integer
      # organization
      field :organization_single, T.nilable(::Easyship::Shared::OrganizationSingle)


      sig { params(content_type: ::String, raw_response: ::Faraday::Response, status_code: ::Integer, organization_single: T.nilable(::Easyship::Shared::OrganizationSingle)).void }
      def initialize(content_type: nil, raw_response: nil, status_code: nil, organization_single: nil)
        @content_type = content_type
        @raw_response = raw_response
        @status_code = status_code
        @organization_single = organization_single
      end
    end
  end
end
