# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Operations
  

    class ListCompaniesRequest < ::Easyship::Utils::FieldAugmented
      extend T::Sig

      # Filter by company name
      field :company_name, T.nilable(::String), { 'query_param': { 'field_name': 'company_name', 'style': 'form', 'explode': true } }
      # Filter by Easyship company ID
      field :easyship_company_id, T.nilable(::String), { 'query_param': { 'field_name': 'easyship_company_id', 'style': 'form', 'explode': true } }
      # Filter by organization ID
      field :organization_id, T.nilable(::String), { 'query_param': { 'field_name': 'organization_id', 'style': 'form', 'explode': true } }
      # Filter by company owner's email
      field :owner_email, T.nilable(::String), { 'query_param': { 'field_name': 'owner_email', 'style': 'form', 'explode': true } }
      # Sort records by listed columns. Default: `created_at`
      field :sort_by, T.nilable(::Easyship::Operations::SortBy), { 'query_param': { 'field_name': 'sort_by', 'style': 'form', 'explode': true } }
      # Set the sort direction. Default: `DESC`
      field :sort_direction, T.nilable(::Easyship::Operations::SortDirection), { 'query_param': { 'field_name': 'sort_direction', 'style': 'form', 'explode': true } }


      sig { params(company_name: T.nilable(::String), easyship_company_id: T.nilable(::String), organization_id: T.nilable(::String), owner_email: T.nilable(::String), sort_by: T.nilable(::Easyship::Operations::SortBy), sort_direction: T.nilable(::Easyship::Operations::SortDirection)).void }
      def initialize(company_name: nil, easyship_company_id: nil, organization_id: nil, owner_email: nil, sort_by: nil, sort_direction: nil)
        @company_name = company_name
        @easyship_company_id = easyship_company_id
        @organization_id = organization_id
        @owner_email = owner_email
        @sort_by = sort_by
        @sort_direction = sort_direction
      end
    end
  end
end
