# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Operations
  

    class ListOrganizationsRequest < ::Easyship::Utils::FieldAugmented
      extend T::Sig

      # Page number to fetch, default: `1`
      field :page, T.nilable(::Integer), { 'query_param': { 'field_name': 'page', 'style': 'form', 'explode': true } }
      # Number of records per page to fetch, default: `20`
      field :per_page, T.nilable(::Integer), { 'query_param': { 'field_name': 'per_page', 'style': 'form', 'explode': true } }


      sig { params(page: T.nilable(::Integer), per_page: T.nilable(::Integer)).void }
      def initialize(page: nil, per_page: nil)
        @page = page
        @per_page = per_page
      end
    end
  end
end
