# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Operations
  
    # SortDirection - Set the sort direction. Default: `DESC`
    class SortDirection < T::Enum
      enums do
        ASC = new('ASC')
        DESC = new('DESC')
      end
    end

  end
end
