# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Operations
  
    # SortBy - Sort records by listed columns. Default: `created_at`
    class SortBy < T::Enum
      enums do
        COMPANY_NAME = new('company_name')
        CREATED_AT = new('created_at')
      end
    end

  end
end
