# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Operations
  

    class UpdateOrganizationsRequest < ::Easyship::Utils::FieldAugmented
      extend T::Sig

      # Organization ID provided when creating the organization
      field :organization_id, ::String, { 'path_param': { 'field_name': 'organization_id', 'style': 'simple', 'explode': false } }

      field :organization_update, T.nilable(::Easyship::Shared::OrganizationUpdate), { 'request': { 'media_type': 'application/json' } }


      sig { params(organization_id: ::String, organization_update: T.nilable(::Easyship::Shared::OrganizationUpdate)).void }
      def initialize(organization_id: nil, organization_update: nil)
        @organization_id = organization_id
        @organization_update = organization_update
      end
    end
  end
end
