# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Shared
  
    # OAuth 2 Client Application
    class Application < ::Easyship::Utils::FieldAugmented
      extend T::Sig

      # OAuth 2 Client Application UID
      field :uid, T.nilable(::String), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('uid') } }


      sig { params(uid: T.nilable(::String)).void }
      def initialize(uid: nil)
        @uid = uid
      end
    end
  end
end
