# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Shared
  
    # Account Detail
    class CompanySingle < ::Easyship::Utils::FieldAugmented
      extend T::Sig


      field :company, T.nilable(::Easyship::Shared::Company), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('company') } }


      sig { params(company: T.nilable(::Easyship::Shared::Company)).void }
      def initialize(company: nil)
        @company = company
      end
    end
  end
end
