# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Shared
  
    # List of Companies
    class CompanyList < ::Easyship::Utils::FieldAugmented
      extend T::Sig


      field :companies, T.nilable(T::Array[::Easyship::Shared::Company]), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('companies') } }

      field :meta, T.nilable(::Easyship::Shared::Meta), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('meta') } }


      sig { params(companies: T.nilable(T::Array[::Easyship::Shared::Company]), meta: T.nilable(::Easyship::Shared::Meta)).void }
      def initialize(companies: nil, meta: nil)
        @companies = companies
        @meta = meta
      end
    end
  end
end
