# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Shared
  

    class Company < ::Easyship::Utils::FieldAugmented
      extend T::Sig

      # Country Code in Alpha-2 format (ISO 3166-1)
      field :country_alpha2, T.nilable(::Easyship::Shared::CountryAlpha2), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('country_alpha2'), 'decoder': Utils.enum_from_string(::Easyship::Shared::CountryAlpha2, true) } }
      # Date and time when the company was created
      field :created_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('created_at'), 'decoder': Utils.datetime_from_iso_format(true) } }
      # Readable identifier prefixed with ES (Easyship) and destination country code
      field :easyship_company_id, T.nilable(::String), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('easyship_company_id') } }
      # Company name
      field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('name') } }

      field :organization, T.nilable(::Easyship::Shared::Organization), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('organization') } }

      field :owner, T.nilable(::Easyship::Shared::CompanyOwner), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('owner') } }
      # Date and time when the company was last updated
      field :updated_at, T.nilable(::DateTime), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('updated_at'), 'decoder': Utils.datetime_from_iso_format(true) } }


      sig { params(country_alpha2: T.nilable(::Easyship::Shared::CountryAlpha2), created_at: T.nilable(::DateTime), easyship_company_id: T.nilable(::String), name: T.nilable(::String), organization: T.nilable(::Easyship::Shared::Organization), owner: T.nilable(::Easyship::Shared::CompanyOwner), updated_at: T.nilable(::DateTime)).void }
      def initialize(country_alpha2: nil, created_at: nil, easyship_company_id: nil, name: nil, organization: nil, owner: nil, updated_at: nil)
        @country_alpha2 = country_alpha2
        @created_at = created_at
        @easyship_company_id = easyship_company_id
        @name = name
        @organization = organization
        @owner = owner
        @updated_at = updated_at
      end
    end
  end
end
