# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Shared
  
    # Error
    class Error < ::Easyship::Utils::FieldAugmented
      extend T::Sig


      field :error, T.nilable(::Easyship::Shared::ErrorError), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('error') } }


      sig { params(error: T.nilable(::Easyship::Shared::ErrorError)).void }
      def initialize(error: nil)
        @error = error
      end
    end
  end
end
