# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Shared
  
    # OAuth2ClientCredentialsRequestGrantType - OAuth 2 Grant Type
    class OAuth2ClientCredentialsRequestGrantType < T::Enum
      enums do
        CLIENT_CREDENTIALS = new('client_credentials')
      end
    end

  end
end
