# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Easyship
  module Shared
    # OAuth 2 Introspect Request
    class OAuth2IntrospectRequest < Easyship::Utils::FieldAugmented
      extend T::Sig

      # OAuth 2 Access Token
      field :token, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('token') } }


      sig { params(token: T.nilable(String)).void }
      def initialize(token: nil)
        @token = token
      end
    end
  end
end
