# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Shared
  
    # OAuth2TokenResponseTokenType - OAuth 2 Token Type
    class OAuth2TokenResponseTokenType < T::Enum
      enums do
        BEARER = new('Bearer')
      end
    end

  end
end
