# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Shared
  
    # List of Organizations
    class OrganizationList < ::Easyship::Utils::FieldAugmented
      extend T::Sig


      field :meta, T.nilable(::Easyship::Shared::OrganizationListMeta), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('meta') } }

      field :organizations, T.nilable(T::Array[::Easyship::Shared::Organization]), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('organizations') } }


      sig { params(meta: T.nilable(::Easyship::Shared::OrganizationListMeta), organizations: T.nilable(T::Array[::Easyship::Shared::Organization])).void }
      def initialize(meta: nil, organizations: nil)
        @meta = meta
        @organizations = organizations
      end
    end
  end
end
