# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Shared
  

    class OrganizationUpdate < ::Easyship::Utils::FieldAugmented
      extend T::Sig

      # Organization name
      field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('name') } }


      sig { params(name: T.nilable(::String)).void }
      def initialize(name: nil)
        @name = name
      end
    end
  end
end
