# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Easyship
  module Shared

    class Organization < Easyship::Utils::FieldAugmented
      extend T::Sig


      field :created_at, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('created_at') } }
      # Organization ID
      field :id, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('id') } }
      # Organization name
      field :name, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('name') } }

      field :updated_at, T.nilable(String), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('updated_at') } }


      sig { params(created_at: T.nilable(String), id: T.nilable(String), name: T.nilable(String), updated_at: T.nilable(String)).void }
      def initialize(created_at: nil, id: nil, name: nil, updated_at: nil)
        @created_at = created_at
        @id = id
        @name = name
        @updated_at = updated_at
      end
    end
  end
end
