# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Shared
  

    class Platform < ::Easyship::Utils::FieldAugmented
      extend T::Sig

      # Platform ID
      field :id, T.nilable(::Integer), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('id') } }
      # Platform Name
      field :name, T.nilable(::String), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('name') } }


      sig { params(id: T.nilable(::Integer), name: T.nilable(::String)).void }
      def initialize(id: nil, name: nil)
        @id = id
        @name = name
      end
    end
  end
end
