# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Shared
  
    # General success response
    class Success < ::Easyship::Utils::FieldAugmented
      extend T::Sig


      field :success, T.nilable(::Easyship::Shared::SuccessSuccess), { 'format_json': { 'letter_case': ::Easyship::Utils.field_name('success') } }


      sig { params(success: T.nilable(::Easyship::Shared::SuccessSuccess)).void }
      def initialize(success: nil)
        @success = success
      end
    end
  end
end
