# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module OpenApiSDK
  module Shared
    # TokenType - OAuth 2 Token Type
    class TokenType < T::Enum
      enums do
        BEARER = new('Bearer')
      end
    end

  end
end
