# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Easyship
  module Shared
  
    # Type - The type of error returned.
    class Type < T::Enum
      enums do
        INVALID_REQUEST_ERROR = new('invalid_request_error')
        API_ERROR = new('api_error')
      end
    end

  end
end
