# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

module Easyship
  autoload :Api, 'easyship/api'
  autoload :Shared, 'easyship/models/shared'
  autoload :Operations, 'easyship/models/operations'
  autoload :Companies, 'easyship/companies'
  autoload :Organizations, 'easyship/organizations'
  autoload :Auth, 'easyship/auth'
end

require_relative 'easyship/utils/t'
require_relative 'easyship/utils/utils'
require_relative 'easyship/utils/metadata_fields'
require_relative 'easyship/sdkconfiguration'
