# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'
require_relative '../shared/pagination'

module Easyship
  module Shared

    class OrganizationListMeta < Easyship::Utils::FieldAugmented
      extend T::Sig

      # Pagination
      field :pagination, T.nilable(Shared::Pagination), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('pagination') } }


      sig { params(pagination: T.nilable(Shared::Pagination)).void }
      def initialize(pagination: nil)
        @pagination = pagination
      end
    end

    # List of Organizations
    class OrganizationList < Easyship::Utils::FieldAugmented
      extend T::Sig


      field :meta, T.nilable(Shared::OrganizationListMeta), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('meta') } }

      field :organizations, T.nilable(T::Array[Shared::Organization]), { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('organizations') } }


      sig { params(meta: T.nilable(Shared::OrganizationListMeta), organizations: T.nilable(T::Array[Shared::Organization])).void }
      def initialize(meta: nil, organizations: nil)
        @meta = meta
        @organizations = organizations
      end
    end
  end
end
